src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentRepository::class)
 */
class Comment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment_text;

    /**
     * @ORM\Column(type="datetime", options={"default"="CURRENT_TIMESTAMP"})
     */
    private $date_posted;

    /**
     * @ORM\Column(type="integer", nullable=true,options={"default"=0})
     */
    private $like_count=0;

    /**
     * @ORM\Column(type="integer", nullable=true,options={"default"=0})
     */
    private $dislike_count=0;

    /**
     * @ORM\ManyToOne(targetEntity=Review::class, inversedBy="comments")
     */
    private $review;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="comments")
     */
    private $user_id;

    public function __construct()
    {
        $this->date_posted = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCommentText(): ?string
    {
        return $this->comment_text;
    }

    public function setCommentText(?string $comment_text): self
    {
        $this->comment_text = $comment_text;

        return $this;
    }

    public function getDatePosted(): ?\DateTimeInterface
    {
        return $this->date_posted;
    }

    public function setDatePosted(?\DateTimeInterface $date_posted): self
    {
        $this->date_posted = $date_posted;

        return $this;
    }

    public function getLikeCount(): ?int
    {
        return $this->like_count;
    }

    public function setLikeCount(?int $like_count): self
    {
        $this->like_count = $like_count;

        return $this;
    }

    public function getDislikeCount(): ?int
    {
        return $this->dislike_count;
    }

    public function setDislikeCount(?int $dislike_count): self
    {
        $this->dislike_count = $dislike_count;

        return $this;
    }

    public function getReview(): ?Review
    {
        return $this->review;
    }

    public function setReview(?Review $review): self
    {
        $this->review = $review;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }
}

src/Form/CommentType.php
<?php

namespace App\Form;

use App\Entity\Comment;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('comment_text')
            ->add('date_posted')
            ->add('like_count')
            ->add('dislike_count')
            ->add('review')
            ->add('user_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Comment::class,
        ]);
    }
}

src/Controller/CommentController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Form\CommentType;
use App\Repository\CommentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/comment")
 */
class CommentController extends AbstractController
{
    /**
     * @Route("/", name="app_comment_index", methods={"GET"})
     */
    public function index(CommentRepository $commentRepository): Response
    {
        return $this->render('comment/index.html.twig', [
            'comments' => $commentRepository->findAll(),
        ]);
    }

    /**
     * @Route("/api/comments", name="api_comment_index", methods={"GET"})
     */
    public function apiIndex(CommentRepository $commentRepository): JsonResponse
    {
        $comments = $commentRepository->findAll();

        $data = [];
        foreach ($comments as $comment) {
            $data[] = [
                'id' => $comment->getId(),
                'comment_text' => $comment->getCommentText(),
                'date_posted' => $comment->getDatePosted()->format('Y-m-d H:i:s'),
                'like_count' => $comment->getLikeCount(),
                'dislike_count' => $comment->getDislikeCount(),
                // If you want to include the review and user details, you can add them as well
                // 'review' => [
                //     'id' => $comment->getReview()->getId(),
                //     'review_text' => $comment->getReview()->getReviewText(),
                // ],
                // 'user' => [
                //     'id' => $comment->getUserId()->getId(),
                //     'username' => $comment->getUserId()->getUsername(),
                // ],
            ];
        }

        return new JsonResponse($data);
    }

    /**
     * @Route("/new", name="app_comment_new", methods={"GET", "POST"})
     */
    public function new(Request $request, CommentRepository $commentRepository): Response
    {
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $commentRepository->add($comment);
            return $this->redirectToRoute('app_comment_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('comment/new.html.twig', [
            'comment' => $comment,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/api/comments/new", name="api_comment_new", methods={"POST"})
     */
    public function apiNew(Request $request, CommentRepository $commentRepository): JsonResponse
    {
        $data = json_decode($request->getContent(), true);

        // Check if the required data (e.g., "comment_text") is provided in the JSON payload
        if (empty($request->get('comment_text'))) {
            return new JsonResponse(['error' => 'Comment text is required.'], JsonResponse::HTTP_BAD_REQUEST);
        }

        // Create a new Comment entity and set its properties based on the data received
        $comment = new Comment();
        $comment->setCommentText($request->get('comment_text'));
        $comment->setLikeCount($request->get('like_count') ?? 0);
        $comment->setDislikeCount($request->get('dislike_count') ?? 0);

        // Assuming the JSON payload contains a valid DateTime string for "date_posted" property
        $datePosted = new \DateTime($request->get('date_posted') ?? 'now');
        $comment->setDatePosted($datePosted);

        // If you want to associate the comment with a review and user, you can do the following:
        // Assuming the JSON payload includes review_id and user_id properties for the respective entities.
        // $review = $entityManager->getRepository(Review::class)->find($data['review_id']);
        // $user = $entityManager->getRepository(User::class)->find($data['user_id']);
        // $comment->setReview($review);
        // $comment->setUserId($user);

        // Persist the new comment to the database
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($comment);
        $entityManager->flush();

        return new JsonResponse(['message' => 'Comment created successfully.'], JsonResponse::HTTP_CREATED);
    }

    /**
     * @Route("/{id}", name="app_comment_show", methods={"GET"})
     */
    public function show(Comment $comment): Response
    {
        return $this->render('comment/show.html.twig', [
            'comment' => $comment,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_comment_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Comment $comment, CommentRepository $commentRepository): Response
    {
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $commentRepository->add($comment);
            return $this->redirectToRoute('app_comment_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('comment/edit.html.twig', [
            'comment' => $comment,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/api/comments/{id}/edit", name="api_comment_edit", methods={"PUT"})
     */
    public function apiEdit(Request $request, Comment $comment, CommentRepository $commentRepository): JsonResponse
    {


        // Check if the required data (e.g., "comment_text") is provided in the JSON payload


        if ($request->get('comment_text') !== null && !empty($request->get('comment_text'))) {
            $comment->setCommentText($request->get('comment_text'));
        }
        if ($request->get('like_count') !== null && !empty($request->get('like_count'))) {
            $comment->setLikeCount($request->get('like_count'));
        }
        if ($request->get('dislike_count') !== null && !empty($request->get('dislike_count'))) {
            $comment->setDislikeCount($request->get('dislike_count'));
        }

        // Update the Comment entity with the new data


        // If you want to associate the comment with a review and user, you can do the following:
        // Assuming the JSON payload includes review_id and user_id properties for the respective entities.
        // $review = $entityManager->getRepository(Review::class)->find($data['review_id']);
        // $user = $entityManager->getRepository(User::class)->find($data['user_id']);
        // $comment->setReview($review);
        // $comment->setUserId($user);

        // Persist the updated comment to the database
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->flush();

        return new JsonResponse(['message' => 'Comment updated successfully.'], JsonResponse::HTTP_OK);
    }

    /**
     * @Route("/{id}", name="app_comment_delete", methods={"POST"})
     */
    public function delete(Request $request, Comment $comment, CommentRepository $commentRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$comment->getId(), $request->request->get('_token'))) {
            $commentRepository->remove($comment);
        }

        return $this->redirectToRoute('app_comment_index', [], Response::HTTP_SEE_OTHER);
    }
    /**
     * @Route("/api/comments/{id}", name="api_comment_delete", methods={"DELETE"})
     */
    public function apiDelete(Request $request, Comment $comment, CommentRepository $commentRepository): JsonResponse
    {
       

        // Remove the comment from the database
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($comment);
        $entityManager->flush();

        return new JsonResponse(['message' => 'Comment deleted successfully.'], JsonResponse::HTTP_OK);
    }
}

templates/comment/_delete_form.html.twig
<form method="post" action="{{ path('app_comment_delete', {'id': comment.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ comment.id) }}">
    <button class="btn">Delete</button>
</form>

templates/comment/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/comment/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Comment{% endblock %}

{% block body %}
    <h1>Edit Comment</h1>

    {{ include('comment/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_comment_index') }}">back to list</a>

    {{ include('comment/_delete_form.html.twig') }}
{% endblock %}

templates/comment/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Comment index{% endblock %}

{% block body %}
    <h1>Comment index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Comment_text</th>
                <th>Date_posted</th>
                <th>Like_count</th>
                <th>Dislike_count</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for comment in comments %}
            <tr>
                <td>{{ comment.id }}</td>
                <td>{{ comment.commentText }}</td>
                <td>{{ comment.datePosted ? comment.datePosted|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ comment.likeCount }}</td>
                <td>{{ comment.dislikeCount }}</td>
                <td>
                    <a href="{{ path('app_comment_show', {'id': comment.id}) }}">show</a>
                    <a href="{{ path('app_comment_edit', {'id': comment.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_comment_new') }}">Create new</a>
{% endblock %}

templates/comment/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Comment{% endblock %}

{% block body %}
    <h1>Create new Comment</h1>

    {{ include('comment/_form.html.twig') }}

    <a href="{{ path('app_comment_index') }}">back to list</a>
{% endblock %}

templates/comment/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Comment{% endblock %}

{% block body %}
    <h1>Comment</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ comment.id }}</td>
            </tr>
            <tr>
                <th>Comment_text</th>
                <td>{{ comment.commentText }}</td>
            </tr>
            <tr>
                <th>Date_posted</th>
                <td>{{ comment.datePosted ? comment.datePosted|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Like_count</th>
                <td>{{ comment.likeCount }}</td>
            </tr>
            <tr>
                <th>Dislike_count</th>
                <td>{{ comment.dislikeCount }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_comment_index') }}">back to list</a>

    <a href="{{ path('app_comment_edit', {'id': comment.id}) }}">edit</a>

    {{ include('comment/_delete_form.html.twig') }}
{% endblock %}